#!/bin/bash

exec 2>&1

mkdir -p "{{pkg.svc_var_path}}/run/log"

echo "Starting pgpool-II"
exec pgpool -a "{{pkg.svc_config_path}}/pool_hba.conf" -f "{{pkg.svc_config_path}}/pgpool.conf" --dont-detach
